import streamlit as st
import requests
import asyncio
import aiohttp
from qdrant_client import QdrantClient
from sentence_transformers import SentenceTransformer

# --- Page Config ---
st.set_page_config(
    page_title="NotionAtlas — AI Semantic Search & RAG for Notion",
    page_icon="🧭",
    layout="wide"
)

# ---------- HEADER & TITLE ----------
st.markdown(
    """
    <div style="display: flex; align-items: center; justify-content: center; margin-bottom: 1.1em;">
        <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png" width="46" style="margin-right:13px">
        <h1 style="display:inline; margin:0 0 0 4px; font-size:2.15em; font-family:sans-serif;">
            NotionAtlas
            <span style="font-weight:400; font-size:0.58em;">— AI Semantic Search & RAG Assistant for Notion</span>
        </h1>
        <a href="https://github.com/Yashraj-Muthyapwar/NotionAtlas-AI-Semantic-Search-And-RAG-Assistant-for-Notion" target="_blank" title="GitHub Repo">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" width="28" style="margin-left:12px;vertical-align:middle"/>
        </a>
    </div>
    """,
    unsafe_allow_html=True
)
st.caption("Supercharge your Notion workspace with instant, context-aware answers powered by advanced AI and semantic search.")

# ---------- SIDEBAR ----------
with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png", width=52)
    st.title("NotionAtlas")
    st.markdown("""
    <span style='font-size:1.12em;'>AI Semantic Search & RAG Assistant for Notion</span>
    - [GitHub Repo](https://github.com/Yashraj-Muthyapwar/NotionAtlas-AI-Semantic-Search-And-RAG-Assistant-for-Notion)
    """, unsafe_allow_html=True)
    st.markdown("---")
    st.markdown("Built by [Yashraj Muthyapwar](https://github.com/Yashraj-Muthyapwar)")

# ---------- TRY ASKING SECTION ----------
st.markdown("""
<div style='padding:18px 24px; background:linear-gradient(90deg, #ece9ff 75%, #fff 100%); border-radius:16px; margin-bottom:1.3em;'>
    <b>💡 Try asking:</b>
    <ul style='margin:0; padding-left:1.2em;'>
        <li>How can I scrape tables from web pages using Pandas?</li>
        <li>Compare Decision Trees and Neural Networks for classification.</li>
        <li>Explain vocabulary and feature extraction in NLP.</li>
    </ul>
</div>
""", unsafe_allow_html=True)

# --- Load Secrets ---
LLAMA_API_URL = "https://api.llama.com/v1/chat/completions"
LLAMA_API_KEY = st.secrets["LLAMA_API_KEY"]
QDRANT_URL = st.secrets["QDRANT_URL"]
QDRANT_API_KEY = st.secrets["QDRANT_API_KEY"]
HF_TOKEN = st.secrets.get("HF_TOKEN", None)

COLLECTION_NAME = "notion_content"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# --- Initialize Clients ---
qdrant = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
embedder = SentenceTransformer(EMBEDDING_MODEL, use_auth_token=HF_TOKEN)

# --- Session State ---
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "conversation_context" not in st.session_state:
    st.session_state.conversation_context = ""

# --- Chat Bubble Utility ---
def chat_bubble(msg, sender="user"):
    color = "#f1f3f4" if sender == "user" else "#e0f7fa"
    icon = "🧑‍💻" if sender == "user" else "🤖"
    align = "flex-start" if sender == "user" else "flex-end"
    st.markdown(
        f"""
        <div style='background-color:{color}; padding:12px 18px; border-radius:16px; margin:8px 0; align-self:{align}; max-width:75%; font-size:1.09em'>
            <span style='font-size:1.2em; margin-right:8px'>{icon}</span>{msg}
        </div>
        """,
        unsafe_allow_html=True
    )

# --- Async Chat Function ---
async def chat_with_memory(user_input: str):
    # 1️⃣ Encode query
    vector = embedder.encode(user_input).tolist()
    
    # 2️⃣ Query Qdrant
    results = qdrant.query_points(
        collection_name=COLLECTION_NAME,
        query=vector,
        limit=5
    )

    # 3️⃣ Prepare semantic context
    context = "\n".join([
        hit.payload.get('chunk_text', '') for hit in results.points
    ]) or "No relevant context found."

    # 4️⃣ Update conversation memory
    st.session_state.conversation_context += f"\nUser: {user_input}"
    combined_context = (
        f"Conversation history:\n{st.session_state.conversation_context}\n\n"
        f"Relevant Notion context:\n{context}"
    )

    # 5️⃣ Call LLAMA API
    payload = {
        "model": "Llama-4-Maverick-17B-128E-Instruct-FP8",
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are NotionAtlas, an AI assistant for Notion workspace queries. "
                    "Use the context if available. If context is insufficient, "
                    "start with: 'Note: This answer is **generated by LLAMA** "
                    "& falls **outside the scope of the Notion workspace data.**'"
                )
            },
            {"role": "user", "content": combined_context}
        ],
        "max_tokens": 500,
        "temperature": 0.2
    }

    headers = {"Authorization": f"Bearer {LLAMA_API_KEY}", "Content-Type": "application/json"}

    async with aiohttp.ClientSession() as session:
        async with session.post(LLAMA_API_URL, json=payload, headers=headers) as resp:
            if resp.status == 200:
                data = await resp.json()
                answer = data["completion_message"]["content"]["text"].strip()
            else:
                answer = f"Error: {await resp.text()}"

    # 6️⃣ Save to chat history and memory
    st.session_state.chat_history.append({"role": "user", "content": user_input})
    st.session_state.chat_history.append({"role": "assistant", "content": answer})
    st.session_state.conversation_context += f"\nAssistant: {answer}"

    return answer

# --- Chat Input ---
st.markdown("---")
user_input = st.chat_input("Ask anything about your Notion workspace...")

if user_input:
    with st.spinner("Thinking..."):
        asyncio.run(chat_with_memory(user_input))

# --- Display Chat History as Chat Bubbles ---
for msg in st.session_state.chat_history:
    if msg["role"] == "user":
        chat_bubble(msg["content"], sender="user")
    else:
        chat_bubble(msg["content"], sender="assistant")

# --- CUSTOM FOOTER & CSS ---
st.markdown(
    """
    <style>
    footer {visibility: hidden;}
    .stTextInput>div>div>input {
        border-radius: 12px;
        border: 1px solid #e0e0e0;
        padding: 10px;
        font-size: 1.08em;
    }
    </style>
    """,
    unsafe_allow_html=True
)
